# Generated by Django 5.0 on 2023-12-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pants', 'Pants'), ('Jacket', 'Jacket'), ('Sweatshirts & Hoodies', 'Sweatshirts & Hoodies'), ('Shoes', 'Shoes'), ('Polo', 'Polo'), ('T-Shirt', 'T-Shirt'), ('Denim', 'Denim'), ('Shorts', 'Shorts')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('KIDS', 'Kids'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5, null=True),
        ),
    ]
