# Generated by Django 5.0 on 2023-12-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auction_auctionbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('auction', 'Auction')], default='sell', max_length=10),
        ),
    ]
