# Generated by Django 5.0 on 2023-12-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_buy_price_product_start_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buy_price',
        ),
    ]
